apiVersion: deployments.plural.sh/v1alpha1
kind: ServiceDeployment
metadata:
  name: terragrunt-samples-stacks
  namespace: default
spec:
  namespace: default
  templated: false
  git:
    url: https://github.com/pluralsh/terragrunt-samples.git
    ref: main
    folder: manifests
    files:
      - cluster.yaml
      - repository.yaml
      - terraform-aws-s3.yaml
      - opentofu-local-file.yaml
      - opentofu-random.yaml
  cluster: mgmt
