apiVersion: deployments.plural.sh/v1alpha1
kind: InfrastructureStack
metadata:
  name: terragrunt-sample-terraform-aws-s3
  namespace: default
spec:
  type: TERRAGRUNT
  repositoryRef:
    name: terragrunt-samples
    namespace: default
  cluster: mgmt
  git:
    ref: main
    folder: terraform-aws-s3
  jobSpec:
    namespace: plrl-deploy-operator
    serviceAccount: stacks
